var coursesArray = [
	{
		key: "1",
		name: "HTML5",
		description: "HTML5 full crash course",
		price: "9.99",
		img: "https://img.icons8.com/color/300/000000/html-5.png",
	},
	{
		key: "2",
		name: "CSS3",
		description: "CSS3 full crash course",
		price: "9.99",
		img: "https://img.icons8.com/color/300/000000/css3.png",
	},
	{
		key: "3",
		name: "Bootstrap4",
		description: "Bootstrap4 full crash course",
		price: "9.99",
		img: "https://img.icons8.com/color/300/000000/bootstrap.png",
	},
	{
		key: "4",
		name: "Sass",
		description: "Sass full crash course",
		price: "5.99",
		img: "https://img.icons8.com/color/300/000000/sass.png",
	},
	{
		key: "5",
		name: "JavaScript",
		description: "Javascript full crash course",
		price: "19.99",
		img: "https://img.icons8.com/color/300/000000/javascript-logo-1.png",
	},
	{
		key: "6",
		name: "React",
		description: "React full crash course",
		price: "19.99",
		img: "https://img.icons8.com/color/300/000000/react-native.png",
	},
	{
		key: "7",
		name: "Angular",
		description: "Angular full crash course",
		price: "12.99",
		img: "https://img.icons8.com/color/300/000000/angularjs.png",
	},
	{
		key: "8",
		name: "Vue",
		description: "Vue full crash course",
		price: "5.99",
		img: "https://img.icons8.com/color/300/000000/vue-js.png",
	},
	{
		key: "9",
		name: "Python",
		description: "Python full crash course",
		price: "29.99",
		img: "https://img.icons8.com/color/300/000000/python.png",
	},
	{
		key: "10",
		name: "PHP",
		description: "PHP full crash course",
		price: "21.99",
		img: "https://img.icons8.com/offices/300/000000/php-logo.png",
	},
	{
		key: "11",
		name: "Java",
		description: "Java full crash course",
		price: "15.99",
		img: "https://img.icons8.com/color/300/000000/java-coffee-cup-logo.png",
	},
	{
		key: "12",
		name: "Ruby",
		description: "Ruby full crash course",
		price: "99.99",
		img: "https://img.icons8.com/officel/300/000000/ruby-programming-language.png",
	},
];

export default coursesArray;